### NumPy

*1. Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк). Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?*

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(6, 2)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [4]:
a1= a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(12, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 3)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [5]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# нет
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
b = a.reshape (12, 1)
a.ndim == b.ndim

False

*2. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.*

In [6]:
a = np.random.randn(3,4)
print(a)
print(a.size)
a = a.flatten()
print(a.size)

[[-0.55920976 -0.56579494  0.38984599 -0.64780814]
 [-0.5837477   0.33789173  0.23110106 -0.32326417]
 [ 1.2775322  -1.09698233  0.7531594   1.47725244]]
12
12


*3. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?*

In [7]:
a = np.arange(20, 0, -2)
print(a)
b = np.arange(20, 1, -2).reshape(1,10)
print(b)
np.array_equal(a, b)

[20 18 16 14 12 10  8  6  4  2]
[[20 18 16 14 12 10  8  6  4  2]]


False

Разница между массивами a и b в том, что a - одномерный, b - двумерный

*4. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.*

In [8]:
a = np.zeros((2, 2))
print("Массив a", a, sep='\n')
b = np.ones((3, 2))
print("Массив b", b, sep='\n')

Массив a
[[0. 0.]
 [0. 0.]]
Массив b
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
v = np.vstack((a, b))
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
v.size

10

*5. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?*

In [11]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
A = a.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
At = A.transpose()
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [14]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [15]:
B.shape


(4, 4)

In [16]:
np.linalg.det(B)

0.0

Вычислить обратную матрицу для B невозможно, т.к. определитель матрицы B равен 0.

*6. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.*

In [17]:
np.random.seed(42)

In [18]:
c = np.random.randint(0, 16,16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


In [19]:
C = c.reshape(4,4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [20]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [21]:
D=B+C*10
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [22]:
# определитель для D.
d = np.linalg.det(D)
print(d)

-28511999.999999944


In [23]:
# ранг для D.
r = np.linalg.matrix_rank(D)
print(r)

4


In [24]:
# обратная матрица D_inv для D.
D_inv=np.linalg.inv(D)
print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


*7. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.*

In [25]:
D_inv = np.where(D_inv < 0, 0,1)
print(D_inv)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [26]:
print("Матрица B", B, sep='\n')
print("Матрица С", C, sep='\n')

Матрица B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица С
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [27]:
E = np.where(D_inv == 1, B, C)
print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
